### PR TITLE
annotations

### PR DESCRIPTION
**Pull request by Cobord**
- Create directed graph when the network-type is directed so the from_hif produces either Graph or DiGraph depending on that
- Use TypedDict rather than an untyped Dict for the validate_hif because there is a fixed set of keys for all the things that can be wrong in the json and the values are only status codes
- Expand the tests so they use validate_hif to see what was wrong (if anything)

### CODE REVIEW

**Comment by nwlandry** [comment]
Hi @Cobord --- thanks for these contributions! Before we review this PR, can you write a description of what this PR changes/addresses/adds? Thanks!

**Comment by colltoaction** [comment]
+1 to Nicholas' comment. FYI I just merged #13 and now this PR has a few conflicts.

**Comment by Cobord** [comment]
Fixed the conflicts

**Comment by colltoaction** [comment]
@Cobord I'm happy to take some of these changes. For example the directed NetworkX graph test and implementation. There is more context you might not have like HNX impl [here](https://github.com/pnnl/HyperNetX/blob/8d53061ea585acc02d5d16c7045db4994a45ad06/hypernetx/classes/hypergraph.py#L1098), but it's a great start.

Is it OK if I ask to leave out non-functional changes? e.g typing, variable renaming. I agree those are good changes but at this time we need to keep it simple.

**Comment by Cobord** [comment]
What is the compatibility restriction? Because of Python ecosystem, that makes sense as typing being treated as not being simple (especially if you need pre-3.5). But renaming constants to capitalization and underscoring unused variables shouldn't have any issue with anywhere else and still be simple.

**Comment by colltoaction** [comment]
We are purposefully ignoring these issues at the moment. This can wait until we set up a linter or similar. In the meantime it makes your changes harder to read.

**Comment by Cobord** [comment]
Cherry picking commit 6f173...
The expanded tests are mixed in with changes not wanting right now so that isn't as cherry pickable

**Comment by nwlandry** [comment]
Hi @Cobord --- thanks for this contribution. From looking at the changes and the corresponding discussion, it seems infeasible to implement right now. I would encourage you to break up this sizable PR into smaller pieces: (1) unit tests for the Github action to run, and (2) handling of directed networks in NetworkX. The contribution for `validate_hif` is not relevant now, because @colltoaction made extensive changes to it. Lastly, the repo is only set up around the schema and unit tests will solely focus on that (not integration tests with other libraries, for example). Again, thanks for the contribution!

**Comment by colltoaction** [comment]
Hi @Cobord, would you like me to help adding the HIF standard to the Hypergraphs library? We've reached a stable schema and there are tutorials for different packages now.

**Pull request closed without merging**
