### PR TITLE
Rewrite the validate_hif.py to use the new schema

### PR DESCRIPTION
**Pull request by colltoaction**
Please let me know if I deleted something I shouldn't have.

### CODE REVIEW

**Comment by colltoaction** [comment]
@nwlandry FYI

**Comment by nwlandry** [comment]
> @nwlandry FYI

Would you like me to review?

**Comment by colltoaction** [comment]
Yes, please take a look a the scripts/hif.py. It had a lot of duplication and many things seemed old.

Thanks!

**Comment by nwlandry** [comment]
Hi @colltoaction --- my only suggested change is to customize the output to improve the clarity of the error messages. Perhaps one way to handle this is to utilize the "messages" field. I think that @pszufe is best to review this PR, since he had an idea of what the output should be.

**Comment by colltoaction** [comment]
Sounds good, thanks for taking a look. @pszufe I'm merging and we can continue this work on the main branch.

**Pull request merged**
